### ISSUE TITLE
SSL wrong version number.

### ISSUE THREAD

**Issue by Fr3akyMurk** [iamtouha/next-lucia-auth#26]
Greetings,
I have an issue on my local build for development where i cannot get the application to properly connect to the DB because of a SSL issue.

I keep getting this issue at:
```
 ⨯ TypeError: fetch failed
    at async login (./src/lib/auth/actions.ts:64:26)
Cause: [Error: 00F88DA8327F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
] {
  library: 'SSL routines',
  reason: 'wrong version number',
  code: 'ERR_SSL_WRONG_VERSION_NUMBER'
}
```

Problem is, this is a completely fresh clone from github, the .env is the only edited part.
How can i solve this error?

**Comment by Fr3akyMurk** [comment]
@iamtouha I forgot to add some details.
For local development i use a locally hosted mysql server, so basically the project is currently completely cut off from the web.
apparently this bug is already known within drizzle and has a workaround for, however this did not help me.
Refer to this [Issue](https://github.com/t3-oss/create-t3-app/issues/1587) for further details.

**Comment by iamtouha** [comment]
Hi @Fr3akyMurk , have you tried removing `?ssl={"rejectUnauthorized":true}` part from DATABASE_URL for local development?

**Comment by Fr3akyMurk** [comment]
Hello, @iamtouha
Yeah i have removed it and tried many different ways to connect to the db but it always results in an error.
I've tried ``?allowPublicKeyRetrieval=true`` and ``&useSSL=false``
Although i am unsure if ``&useSSL=false``does any change, it certainly doesn't when used in practice.

My connection string looks like this, it's quite similar to planetscales url.
```
mysql://<user>:<password>@localhost:3306/luciatest?allowPublicKeyRetrieval=true&useSSL=false
```

**Comment by Fr3akyMurk** [comment]
Okay so, i did some digging.
I played around and changed a few things.

More prominently, i checked the migration code and applied it to the index file.

This seems to resolve the connection issues but then the code starts to complain about an await statement in a top level module.

```javascript
import mysql from "mysql2/promise";
//import { drizzle } from "drizzle-orm/planetscale-serverless";
import { drizzle } from "drizzle-orm/mysql2";
//import { Connection } from "@planetscale/database";

import { env } from "@/env";
import * as schema from "./schema";

//export const connection = new Connection({ url: env.DATABASE_URL });
//export const db = drizzle(connection, { schema });

const connection = await mysql.createConnection(env.DATABASE_URL);
export const db = drizzle(connection, { schema, mode: "default" })
```

Figured this information would be better off to be sent to you considering you made majority of the code.

```
Unhandled Runtime Error

Error: await is only valid in async functions and the top level bodies of modules
Call Stack
(action-browser)/./src/server/db/index.ts
/home/mark/nextjs-typescript-starter/next-lucia-auth/.next/server/app/(auth)/login/page.js (904:1)
```

**Comment by iamtouha** [comment]
`mysql.createConnection` is not an async function. please remove the `await` before the function call and see if the error persists.

**Comment by Fr3akyMurk** [comment]
That is true, ```mysql.createConnection``

**Comment by iamtouha** [comment]
dang! use await before `mysql.createConnection`.
which node version are you using? also, what is set on your `compileropsions.taget` value in tsconfig file?

**Comment by Fr3akyMurk** [comment]
Alright, i have reverted to the code that was posted.
I use node 20.9.0, i am aware that newer versions are available but right now i doubt it's relevant.
I think you meant ``compilerOptions.target``, to answer, it's currently set at "es2022".

I also thought a bit about it, but it could be that the connection still fails but we don't know that because the code running fails before the connection even happens, i will have to check mysql logs if i want to know if the app even connects.

**Comment by iamtouha** [comment]
@Fr3akyMurk  No. drizzle connects smoothly with planetscale using DB_URL

**Comment by Fr3akyMurk** [comment]
Well yeah, and so does it with any local databases, however this time it just has issues.
To be fair i have never used mysql with connectionsteings in projects before so i don't really know what the issue may be.

**Comment by Fr3akyMurk** [comment]
I do not understand anything with this.
It is not a problem on my system only as i have tried this on my main computer, my laptop and a vm.
The error persists either way.

There is little to no documentation on this error and how to fix it.
Using Planetscales link to connect does not work because i get the same SSL issue (different issue but still SSL related)

How do you develop the project? Locally or somehow in the cloud?
I am unaware of any way to develop directly in the cloud.

**Comment by iamtouha** [comment]
Could you please spare some time to create a PR with the changes you made? I will add these changes to a new branch so that someone facing the same problem will benefit.

**Comment by Fr3akyMurk** [comment]
Alright, i will look into it.

**Comment by Fr3akyMurk** [comment]
I will not add my changes, those changes are not reasonable.
However Kinfish (the other contributor) found a much better solution, he uses pg drivers instead of mysql promise based drivers, i will look into that and if it works i will open a pr with that solution for you to view.

My edits are too dramatic for something so simple.
