### ISSUE TITLE
Redirect too fast for form to handle. (Register page)

### ISSUE THREAD

**Issue by Fr3akyMurk** [iamtouha/next-lucia-auth#44]
**Describe the bug**
The form gets redirected as soon as possible ~~(100ms that i saw)~~ (This was code for the editor, not sign in.)  which is way too soon for the db to even get a request and thus you get redirected without your account being created.
This seems to only affect users like me who do not use planetscale but for best practices it could be a great idea to implement a more stable fix.

**To Reproduce**
* Get my code from #40 and configure a local mysql server.
* Run db:push
* Go to sign up page and register.

**Expected behavior**
An account being created before you get redirected, or alternatively sign the user in immediately after creating the account.

**Screenshots**
Not applicable, a video would be more suitable for this type of issue.

**Comment by Fr3akyMurk** [comment]
#46 PR opened.

**Comment by Fr3akyMurk** [comment]
Surprisingly, login page does not do this, only the signup page.

**Comment by iamtouha** [comment]
This occurred because the link component wraps the button and the button submits the form when clicked.
