### ISSUE TITLE
Server actions issues

### ISSUE THREAD

**Issue by firstaxel** [iamtouha/next-lucia-auth#50]
**Describe the bug**
A clear and concise description of what the bug is
Error with the server actions used for auth in the template.

**To Reproduce**
1. Go to auth page 
2. And try to login or sign up 

**Expected behavior**
I am getting async await error await are supposed to be used in async functions I tried to find out the issues but I think it is directly from the functions itself 

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, edge, brave ]

**Comment by Fr3akyMurk** [comment]
This seems like an error i used to have, please send the error log that you get, don't just say "I have an error on login" as that is not enough information for us to process.

**Comment by firstaxel** [comment]
sorry for the misdirection the error gets displayed as i trigger the auth server actions from the auth related pages, including login, register , even the forget password pages, 
i used a local database and this is on my local machine  
![Screenshot from 2024-03-10 19-43-44](https://github.com/iamtouha/next-lucia-auth/assets/123889642/f7529ef3-b7ea-46f4-a396-7df7c0aea9e9)

this is the screenshot i got from my browser and from my code editor
![Screenshot from 2024-03-10 19-43-19](https://github.com/iamtouha/next-lucia-auth/assets/123889642/c71b8e74-01fc-4bcf-a870-2262cb47c3b5)

**Comment by Fr3akyMurk** [comment]
Refer to this [issue.](https://github.com/iamtouha/next-lucia-auth/issues/40)

This app was made to use planetscale and be hosted on vercel not with local db's in mind.
(this method only supports mysql and is not really tested for long periods but it will solve your issues)

**Comment by firstaxel** [comment]
Thanks very much the error is gone finally
